language: node_js
node_js:
 - "node"

cache: npm

script: npm run build && mv ./dist/official-website/* ./dist/ && rm -r ./dist/official-website

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master